[build-system]
build-backend = 'setuptools.build_meta'
requires = ['setuptools>=65.5.0', 'wheel']

[project]
authors = [
    {name = 'Stefano Ubbiali', email = 'subbiali@phys.ethz.ch'},
]
description = 'Common utilities and dotfiles'
name = 'hpc_scripts_common'
readme = {file = 'README.md', content-type = 'text/markdown'}
version = '0.0'

[tool.setuptools.packages.find]
where = ["src/"]
include = ["hpc_scripts.common"]
namespaces = true
